# Generated by Django 3.1.2 on 2020-10-04 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_balance', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date of investment')),
                ('amount_usd', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date of commitment')),
                ('amount_usd', models.FloatField(default=0.0)),
                ('fund_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capitalcallapp.fund')),
            ],
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_usd', models.FloatField(default=0)),
                ('fund_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capitalcallapp.commitment')),
                ('investment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capitalcallapp.investment')),
            ],
        ),
    ]
