# Generated by Django 3.1.2 on 2020-10-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capitalcallapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commitment',
            old_name='fund_id',
            new_name='fund',
        ),
        migrations.AddField(
            model_name='fund',
            name='fund_number',
            field=models.IntegerField(default=0),
        ),
    ]
