# Generated by Django 3.1.2 on 2020-10-05 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capitalcallapp', '0002_auto_20201004_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='fund_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capitalcallapp.fund'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='fund_number',
            field=models.IntegerField(unique=True),
        ),
    ]
