# Generated by Django 3.1.2 on 2020-10-05 11:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('capitalcallapp', '0003_auto_20201005_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call',
            old_name='fund_id',
            new_name='fund',
        ),
        migrations.AddField(
            model_name='call',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of call'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investment',
            name='investment_number',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
