# Generated by Django 3.1.2 on 2020-10-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capitalcallapp', '0004_auto_20201005_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call',
            old_name='investment_id',
            new_name='investment',
        ),
        migrations.AddField(
            model_name='call',
            name='commitment_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='call',
            name='investment_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
