# Generated by Django 3.1.2 on 2020-10-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capitalcallapp', '0005_auto_20201005_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitment',
            name='commitment_number',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
