# Generated by Django 3.1.2 on 2020-10-06 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capitalcallapp', '0006_commitment_commitment_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fund',
            old_name='fund_number',
            new_name='field_fund_id',
        ),
        migrations.RenameField(
            model_name='fund',
            old_name='current_balance',
            new_name='field_initial_balance',
        ),
    ]
