# Generated by Django 3.1.2 on 2020-10-06 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capitalcallapp', '0007_auto_20201006_1026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fund',
            old_name='field_fund_id',
            new_name='fund_number',
        ),
        migrations.RenameField(
            model_name='fund',
            old_name='field_initial_balance',
            new_name='initial_balance',
        ),
    ]
